#!/bin/sh
k=$1
if [ -z "$1" ]; then
	for nombre in 5 4 3 2 1
	do
		printf '%s\n' $nombre
		sleep 1
	done

elif [ "$#" -gt 1 ]; then
	printf '%s\n' "Fuck les études"
	exit 0

elif [ "$1" -le 0 ]; then
	printf '%s\n' "Fuck this shit"
	exit 0

else 
	while [ $k -gt 0 ]; do
		printf '%d\n' $k
		sleep 1
		k=$(($k - 1))
	done
fi

printf 'BOUM !\n'