#!/bin/sh
nb_essai=0
frite=$(awk 'BEGIN { srand(); print int(rand()*1001) }')
read test
printf '%d\n' $frite
printf '%d\n' $test

while [ $test -ne $frite ]; do
    if [ $test -lt $frite ]; then
        printf 'Le nombre recherché est plus grand\n'
        nb_essai=$(($nb_essai + 1))
        read test

    elif [ $test -gt $frite ]; then
        printf 'Le nombre recherché est plus petit\n'
        nb_essai=$(($nb_essai + 1))
        read test
    fi
done

if [ $test -eq $frite ]; then
    printf 'Félicitations ! Vous avez trouvé le nombre secret qui est : %d en %d essais\n' $frite $nb_essai
fi