#!/bin/sh

read nb_secret
temp=0

devine=$(awk 'BEGIN { srand(); print int(rand()*1001) }')
printf 'Je choisis le nombre : %d\n' $devine

while [ "$reponse" != "=" ]; do
    read reponse

    if [ $reponse = '>' ]; then
        printf "OK je vois, j'augmente le nombre\n"
        temp=$((1000 - $devine))
        devine=$(($devine + $(awk "BEGIN { srand(); print int(rand()*$temp) }")))
        printf 'DEVINE = %d\n' $devine
        printf 'Je choisis le nombre suivant : %d\n' $devine

    elif [ $reponse = '<' ]; then
        printf "OK je vois, je diminue le nombre\n"
        devine=$(($devine - $(awk "BEGIN { srand(); print int(rand()*$devine) }")))
        printf 'DEVINE = %d\n' $devine
        printf 'Je choisis le nombre suivant : %d\n' $devine
    fi
done